### ISSUE TITLE
staffeln support in Atmosphere

### ISSUE THREAD

**Issue by ricolin** [vexxhost/atmosphere#586]
This track staffeln support in Atmoshpere
Few tasks to be done:
- [x] Staffeln image publish (we still have Unauthorized when publish staffeln image on quary.io after built one) (see https://github.com/vexxhost/staffeln/actions/runs/6181208321/job/16778839169#step:7:775 )
- [x] Staffeln charts https://github.com/vexxhost/staffeln/issues/107 (This can be consider as a follow up action)
- [x] https://github.com/vexxhost/atmosphere/issues/593 Staffeln roles and add chart for Vexxhost/staffeln ( https://github.com/vexxhost/atmosphere/compare/main...staffeln-support )
- [x] Change lock backend driver ( as content here https://github.com/vexxhost/atmosphere/pull/582 ) ( https://github.com/vexxhost/staffeln/issues/111 )

**Comment by mnaser** [comment]
@ricolin The image has been published to GHCR:

https://github.com/vexxhost/staffeln/pkgs/container/staffeln
